### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by maidou2l** [RRdmlearning/Machine-Learning-From-Scratch#1]
from utils import train_test_split, normalize, accuracy_score, Plot
ImportError: cannot import name 'train_test_split'

**Comment by yky18175633359** [comment]
新人，运行各种问题，硬生生研究了两天。
发现包的导入有点问题，改了之后装点组件就OK了，不过真的感谢。
导入语句部分修改如下
from utils.data_manipulation import train_test_split,standardize, to_categorical#
from utils.data_operation import mean_squared_error,accuracy_score
from utils.loss_functions import SquareLoss
from utils.misc import bar_widgets, Plot
from gradient_boosting_decision_tree.gbdt_model import GBDTRegressor

**Comment by RRdmlearning** [comment]
import error
you can use sys.path.append(project dir)
